---

- name: install borgbackup
  pacman:
    name: borg
    state: present

- name: install cron
  pacman:
    name: cronie
    state: present

- name: enable cron with systemd
  systemd:
    daemon_reload: yes
    service: cronie
    enabled: yes
    state: started

