---

- name: download borg binary
  get_url:
    url: "{{ borgbackup_binary_uri }}"
    dest: "{{ borgbackup_binary }}-{{ borgbackup_binary_version }}"
    mode: "755"

- name: link install
  file:
    src: "{{ borgbackup_binary }}-{{ borgbackup_binary_version }}"
    dest: "{{ borgbackup_binary }}"
    state: link
    force: yes
